### ISSUE TITLE
Фильтр по областям работает некорректно 

### ISSUE THREAD

**Issue by hvadym** [ria-com/auto-ria-rest-api#11]
Посылаю запрос:
`https://developers.ria.com/auto/search?category_id=1&marka_id=6&s_yers=2000&state_id=10&custom=0&damage=0&under_credit=0&confiscated_car=0&auto_repairs=0&abroad=0&sellerType=1&top=4&saledParam=2&countpage=100&api_key=...`
в ответ получаю только 29 ID с 10 (Киевской) области , остальные с других областей. 

По Львову вообще порядка 10.

**Comment by Denysria** [comment]
Здравствуйте.
Мы проверим что могло вызвать неисправность.

**Comment by hvadym** [comment]
@Denysria, спасибо.

**Comment by Denysria** [comment]
Причина некорректной работы фильтра по областям состоит в параметры **state_id**,
что бы фильтр работал коректно нужно указывать **state=10** 
`https://developers.ria.com/auto/search?category_id=1&marka_id=6&s_yers=2000&state=10&custom=0&damage=0&under_credit=0&confiscated_car=0&auto_repairs=0&abroad=0&sellerType=1&top=4&saledParam=2&countpage=100&api_key=....`

**Comment by hvadym** [comment]
@Denysria, спасибо.
