### ISSUE TITLE
Добрый день, подскажите есть ли возможность получить номер телефона продавца через API ?

### ISSUE THREAD

**Issue by rx350h** [ria-com/auto-ria-rest-api#12]
в частности с dom.ria.ua

**Comment by Denysria** [comment]
Здравствуйте!
На сегодняшний день данный функционал не реализован

**Comment by rx350h** [comment]
А в будущем он будет реализован? Или это не сделано в целях безопасности?

**Comment by Denysria** [comment]
Пока не планируеться
