### ISSUE TITLE
Параметр options в методе search игнорируется

### ISSUE THREAD

**Issue by OlehLuk** [ria-com/auto-ria-rest-api#13]
Здравствуйте,

в документации для поиска автомобилей указан параметр options, для указания желаемых опций.
Но почему-то, при запросах на поиск этот параметр игнорируется. Другими словами, два следующих GET запроса дают одинаковый результат.
`https://developers.ria.com/auto/search?api_key=API_KEY&category_id=1&currency=1&options[0]=496`

и

`https://developers.ria.com/auto/search?api_key=API_KEY&category_id=1&currency=1`

Подскажите, пожалуйста, это баг или этот параметр нужно использовать как-то по-другому?

Заранее спасибо.

**Comment by Denysria** [comment]
Здравствуйте,
произошла ошибка, в документации не верно указан параметр options
правильно будет указать auto_options=496, тогда вы получите корректные данные

**Comment by OlehLuk** [comment]
Спасибо за быстрый ответ. Исправьте название параметра в документации, пожалуйста.

**Comment by Denysria** [comment]
Уже исправили

**Comment by OlehLuk** [comment]
В таблице параметров осталось старое название.
Вот [здесь](https://github.com/ria-com/auto-ria-rest-api/tree/master/AUTO_RIA_API#%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2)

**Comment by Denysria** [comment]
ошибка исправлена

**Comment by OlehLuk** [comment]
Спасибо.
