### ISSUE TITLE
Как получить список всех объявлений

### ISSUE THREAD

**Issue by Andrew-Nedelenko** [ria-com/auto-ria-rest-api#15]
При попытке сделать запрос, по примеру из документации https://developers.ria.com/auto/new/autos?user_id=МОЙИД&api_key=МОЙКЛЮЧ, приходит вот такой ответ "message": "You not have permissins for this request!",  на другие запросы, например, категории, все ок. Как получить все объявления?

**Comment by Denysria** [comment]
Добрый день.
Для того что бы получить данный вам нужно перейти в личный кабинет https://developers.ria.com/account/credentials#
затем перейти в раздел "Мои разрешения", напротив нужного вам API вы увидите кнопку "Редактировать", нажмите на нее и отметьте те методы которые хотите использовать

**Comment by Andrew-Nedelenko** [comment]
Благодарю, все получилось
