### ISSUE TITLE
Вопросы по апи

### ISSUE THREAD

**Issue by SHASHA184** [ria-com/auto-ria-rest-api#28]
1. Как искать объявления по улице с помощью апи(я пытался по street-id как и на сайте, но выдает только к-во)
2. Можно ли получить среднюю цену по улице/району(я пытался по id району, но именно из-за этого параметра не находит ничего)

**Comment by SHASHA184** [comment]
Нашел решение

**Comment by siditav** [comment]
Вы знаете, как создать бота для получения товаров со скидкой на aliexpress? говорить свою телеграмму
