### ISSUE TITLE
Вопрос по classifieds

### ISSUE THREAD

**Issue by kuzzmi** [ria-com/auto-ria-rest-api#3]
Здравствуйте, есть ли возможность из значений в classifieds получить URL объявления?
И в одинаковом ли порядке значения classifieds и prices?

**Comment by Denysria** [comment]
Здравствуйте!
В ближайшее время (ориентировочно в течении одной недели) мы запустим новый API v.2.0, в котором будет доступен сервис для получения информации по ID объявления, а также API поиска. Информацию об API v.2.0 Вы сможете найти на нашей странице GitHub.
Записи в поля "classifields" и "prices" идут в одинаковом порядке.

**Comment by kuzzmi** [comment]
Отлично, большое спасибо за информацию и проделанную работу :+1: !
