### ISSUE TITLE
Не работает поиск по двум параметрам?

### ISSUE THREAD

**Issue by iamraccoon** [ria-com/auto-ria-rest-api#5]
Запросы:
https://developers.ria.com/auto/search?api_key=dBkMcJoWz5OD1k6CH1AERgUMFNQwXlNNZfiteIwg&top=1&сategory_id=9
https://developers.ria.com/auto/search?api_key=dBkMcJoWz5OD1k6CH1AERgUMFNQwXlNNZfiteIwg&top=1&сategory_id=1

возвращают идентичный результат. Но, если убрать параметр top, то ответы разные. Получается, что нельзя одновременно искать по двум параметрам?

**Comment by SamhainG** [comment]
Здравствуйте.

В ваших примерах в названии параметра category_id содержится кириллический символ "с" вместо латинского.

**Comment by iamraccoon** [comment]
Был копипаст из https://github.com/ria-com/auto-ria-rest-api/tree/master/AUTO_RIA_API из таблички **Список параметров**

Исправте доку)

**Comment by SamhainG** [comment]
Спасибо. Исправил
