### ISSUE TITLE
Бага с получением списка всех цветов

### ISSUE THREAD

**Issue by iamraccoon** [ria-com/auto-ria-rest-api#6]
https://developers.ria.com/auto/colors?api_key=dBkMcJoWz5OD1k6CH1AERgUMFNQwXlNNZfiteIwg - **404 Not Found**

Или на https://github.com/ria-com/auto-ria-rest-api/tree/master/AUTO_RIA_API#Цвета не тот урл?

**Comment by Denysria** [comment]
Здравствуйте.
Проблема исправлена. Проверьте пожалуйста еще раз
