### ISSUE TITLE
Не работает фильтр по двум параметрам для подсчета средней цены?

### ISSUE THREAD

**Issue by OleksiiZubko** [ria-com/auto-ria-rest-api#9]
Здравствуйте, 

запросы: `https://developers.ria.com/auto/average_price?api_key=API_KEY&marka_id=56&model_id=509&state_id=5&body_id=3` 
и 
`https://developers.ria.com/auto/average_price?api_key=API_KEY&marka_id=56&model_id=509&state_id=18&body_id=3`

работают нормально, но если сделать запрос з двумя параметрами региона:
`https://developers.ria.com/auto/average_price?api_key=API_KEY&marka_id=56&model_id=509&state_id=5&state_id=18&body_id=3`
 то они игнорируются. Нет возможности смотреть среднюю цену по нескольким регионам одновременно?

Спасибо!

**Comment by SamhainG** [comment]
Здравствуйте.

Увы, но на данный момент такая возможность не реализована. В [таблице](https://github.com/ria-com/auto-ria-rest-api#Список-поддерживаемых-параметров) у всех параметров, которые можно передавать массивом, в колонке "Тип данных" присутствуют квадратные скобки.

И еще одна просьба - не публикуйте ваш api-ключ в открытых источниках. Это ваша персональная информация, ею могут воспользоваться третьи лица.

**Comment by OleksiiZubko** [comment]
Понял. Спасибо. 

А планируется в будущем? Если да, можно в feature request перевести, если нет, то close.
